# Site settings
title: "Verbuise: The Globalization Runtime"
email: hello@verbuise.com
description: >-
  Verbuise is the globalization runtime for modern products. Automatically adapt language,
  currency, images, and tone for every marketâ€”no workflow, no rebuilding. The Stripe for going global.
baseurl: ""
url: "https://verbuise.com"
twitter_username: verbuise

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year/:title

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
